name = "edge-chat-demo"
type = "javascript"
workers_dev = true
compatibility_date = "2021-11-08"
# Add your account ID here
account_id = ""

[build.upload]
format = "modules"
dir = "src"
main = "./chat.mjs"
# [works] the following line correctly serves the javascript file
# rules = [{type = "Data", globs = ["**/*.js"]}]
# [doesn't work] the following line does *not* serve the javascript file correctly
rules = [{type = "Data", globs = ["**/*.html"]}, {type = "Data", globs = ["**/*.js"]}]

[durable_objects]
bindings = [
  { name = "rooms", class_name = "ChatRoom" },
  { name = "limiters", class_name = "RateLimiter" }
]

# Indicate that you want the ChatRoom and RateLimiter classes to be callable as Durable Objects.
[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["ChatRoom", "RateLimiter"]
